@startuml
autonumber
opt FairPlay (Safari)
    Website -> "Certificate Store": Get FairPlay Certificate
    Website <- "Certificate Store": {fairplay.cer}
end
Website -> "Catalog API": GET /api/catalog/videos
Website <- "Catalog API": {video1, video2, ...}
Website -> Website: Play video 1
Website -> "Entitlement Service": GET /api/tokens/video1
Website <- "Entitlement Service": {licenseToken}
Website -> Player: Play video 1 {video1.url, licenseToken, [fairPlayCertificate]}
Player -> "License Service": Get license {licenseToken}
Player <- "License Service": {license}
Player -> Player: Playback...
@enduml